version: '3.8'

services:
  # nginx server
  nginx:
    image: nginx:latest
    container_name: trustport-nginx
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl-certs:/etc/ssl/certs:ro
      - ./ssl-private:/etc/ssl/private:ro
      - ./certbot-www:/var/www/certbot
    depends_on:
      - nest-app

  # Certbot for SSL
  certbot:
    image: certbot/certbot
    volumes:
      - ./ssl-certs:/etc/letsencrypt/live
      - ./ssl-private:/etc/letsencrypt/archive
    command: certonly --webroot --webroot-path=/var/www/certbot --email cristian.gonzalez@c3l.io -d api.trustport.cristian-gonzalez.dev --non-interactive --agree-tos --force-renewal

  # NestJS application
  nest-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: trustport-nest
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - postgres

  # Postgres configuration
  postgres:
    image: postgres:latest
    container_name: trustport-postgres
    restart: always
    environment:
      POSTGRES_USER: trustport_db
      POSTGRES_PASSWORD: trustport_db
      POSTGRES_DB: trustport_db
    volumes:
      - postgres-data-trustport:/var/lib/postgresql/data

volumes:
  postgres-data-trustport:
  ssl-certs:
  ssl-private:
